### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by benjamin-actyx** [actyx-contrib/react-pond#7]
In case the user does not pass an `onError` callback, `<Pond />` will forever render `loadComponent`.
But it would probably be better to render sth. like `"An irrecoverable error occured: {error}"` and maybe a button to re-try starting the Pond.

The same applies to `onStoreConnectionClosed`.

**Comment by Alexander89** [comment]
In my opinion, the UX part should be done by the integrator.

WDYT: Is https://github.com/actyx-contrib/react-pond/pull/10 already a sufficient solution?

**Comment by benjamin-actyx** [comment]
That PR does what I had in mind :)
